# ===============================
# APP
# ===============================
spring.application.name=bff-service
server.port=9191

# ===============================
# CONTRACT PACKAGE
# ===============================
spring.kafka.consumer.properties.spring.json.trusted.packages=com.harsha.contracts.*

# ===============================
# BASE URLs
# ===============================
inv-intelligence-url=http://localhost:8084
market-intelligence-url=http://localhost:8083
market-data-url=http://localhost:8080