# ===============================
# APP
# ===============================
spring.application.name=analysis-service
server.port=8081

# ===============================
# KAFKA - COMMON
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# CONSUMER CONFIG
# ===============================
spring.kafka.consumer.group-id=analysis-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# IMPORTANT: your actual package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.harsha.events.core,com.harsha.market.events

# IMPORTANT: your envelope class
spring.kafka.consumer.properties.spring.json.value.default.type=com.harsha.events.core.EventEnvelope

spring.kafka.consumer.properties.spring.json.use.type.headers=false

# ===============================
# PRODUCER CONFIG
# ===============================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

# ===============================
# LISTENER
# ===============================
spring.kafka.listener.ack-mode=record

# ===============================
# TOPICS (custom)
# ===============================
topic.market.ticks=market-stock-ticks
topic.market.ticks.dlt=market-stock-ticks-dlt
topic.analysis.stock.features=analysis-stock-features
topic.analysis.stock.features.dlt=analysis-stock-features-dlt
# ===============================
# DATABASE (Inbox)
# ===============================
#spring.datasource.url=jdbc:h2:file:./data/analysisdb;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://localhost:5432/analysisdb
spring.datasource.username=postgres
spring.datasource.password=2000319

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


