# ===============================
# APP
# ===============================
spring.application.name=investment-intelligence-service
server.port=8084

# ===============================
# KAFKA - COMMON
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# CONSUMER CONFIG
# ===============================
spring.kafka.consumer.group-id=investment-intelligence-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# ===============================
# CONTRACT PACKAGE
# ===============================
spring.kafka.consumer.properties.spring.json.trusted.packages=com.harsha.contracts.*

# ===============================
# ENVELOPE CLASS
# ===============================
spring.kafka.consumer.properties.spring.json.value.default.type=com.harsha.contracts.messaging.EventEnvelope

spring.kafka.consumer.properties.spring.json.use.type.headers=false

# ===============================
# PRODUCER CONFIG
# ===============================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

# ===============================
# LISTENER
# ===============================
spring.kafka.listener.ack-mode=record

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/investment_intelligence_db
spring.datasource.username=postgres
spring.datasource.password=2000319

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# CSE API CONFIG
# ===============================how
cse-base-url: https://www.cse.lk/api

# ===============================
# GROQ CONFIG
# ===============================
llm.provider-type=GROQ
#llm.model=llama-3.3-70b-versatile
llm.model=openai/gpt-oss-120b\
#llm.model=qwen/qwen3-32b
llm.api-key=${GROQ_API_KEY}
llm.base-url=https://api.groq.com/openai/v1

spring.ai.openai.base-url=https://api.groq.com/openai/v1

spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.embedding.enabled=false
