# ===============================
# APP
# ===============================
spring.application.name=strategy-service
server.port=8081

# ===============================
# KAFKA - COMMON
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# CONSUMER CONFIG
# ===============================
spring.kafka.consumer.group-id=strategy-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# ===============================
# CONTRACT PACKAGE
# ===============================
spring.kafka.consumer.properties.spring.json.trusted.packages=com.harsha.contracts.*

# ===============================
# ENVELOPE CLASS
# ===============================
spring.kafka.consumer.properties.spring.json.value.default.type=com.harsha.contracts.messaging.EventEnvelope

spring.kafka.consumer.properties.spring.json.use.type.headers=false

# ===============================
# PRODUCER CONFIG
# ===============================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

# ===============================
# LISTENER
# ===============================
spring.kafka.listener.ack-mode=record

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/strategydb
spring.datasource.username=postgres
spring.datasource.password=2000319

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true